files:
  "/etc/nginx/conf.d/proxy.conf":
    mode: "000644"
    owner: root
    group: root
    content: |
      http {
          types_hash_max_size 2048;
          types_hash_bucket_size 128;
      }
container_commands:
  01_test_nginx_config:
    command: "nginx -t"
  02_restart_nginx:
    command: "service nginx restart"
    ignoreErrors: false
